name: Sync
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to HF
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/${{ github.repository }}.git"
          source_branch: "main"
          destination_repo: "https://echo8900:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/echo8900/claw"
          destination_branch: "main"
